import type { DashboardData } from "./types";

export const mockDashboardData: DashboardData = {
  rankings: [
    {
      ticker: "ATW",
      name: "Attijariwafa Bank",
      sector: "Banking",
      ai_score: 84,
      rank_position: 1,
      liquidity_score: 87,
      quality_score: 88,
      momentum_score: 72,
      risk_score: 38,
      rationale: "High quality and liquidity, but banking concentration needs monitoring.",
      signal: "HOLD",
      confidence: 76,
      reason: "Quality and liquidity are strong, but sector exposure is already meaningful.",
      risk_note: "Watch banking concentration.",
      latest_price_mad: 480,
      daily_change_pct: 1.2,
      momentum_1m: 0.028,
      momentum_3m: 0.072,
    },
    {
      ticker: "IAM",
      name: "Maroc Telecom",
      sector: "Telecom",
      ai_score: 79,
      rank_position: 2,
      liquidity_score: 82,
      quality_score: 80,
      momentum_score: 55,
      risk_score: 30,
      rationale: "Defensive dividend profile with lower volatility.",
      signal: "BUY",
      confidence: 73,
      reason: "Defensive dividend profile fits balanced manual portfolios.",
      risk_note: "Confirm latest source timestamp before relying on signal.",
      latest_price_mad: 91,
      daily_change_pct: -0.4,
      momentum_1m: 0.012,
      momentum_3m: 0.031,
    },
    {
      ticker: "LHM",
      name: "LafargeHolcim Maroc",
      sector: "Materials",
      ai_score: 74,
      rank_position: 3,
      liquidity_score: 62,
      quality_score: 76,
      momentum_score: 73,
      risk_score: 61,
      rationale: "Improving volume and trend, but concentration risk can be high.",
      signal: "SELL",
      confidence: 69,
      reason: "Manual portfolio concentration is high relative to the risk profile.",
      risk_note: "Review single-name exposure.",
      latest_price_mad: 1780,
      daily_change_pct: -5.8,
      momentum_1m: 0.034,
      momentum_3m: 0.085,
    },
    {
      ticker: "BOA",
      name: "Bank of Africa",
      sector: "Banking",
      ai_score: 71,
      rank_position: 4,
      liquidity_score: 75,
      quality_score: 72,
      momentum_score: 68,
      risk_score: 49,
      rationale: "Balanced banking exposure with improving momentum, but sector overlap should be reviewed.",
      signal: "HOLD",
      confidence: 67,
      reason: "Momentum is improving, while banking-sector concentration remains a watch point.",
      risk_note: "Review banking-sector exposure before increasing allocation.",
      latest_price_mad: 185,
      daily_change_pct: 2.1,
      momentum_1m: 0.019,
      momentum_3m: 0.066,
    },
    {
      ticker: "TQM",
      name: "Taqa Morocco",
      sector: "Utilities",
      ai_score: 68,
      rank_position: 5,
      liquidity_score: 58,
      quality_score: 74,
      momentum_score: 54,
      risk_score: 42,
      rationale: "Defensive utility profile, but liquidity and momentum are not strong enough for a positive signal.",
      signal: "HOLD",
      confidence: 63,
      reason: "Defensive profile is useful for monitoring, but signal strength is moderate.",
      risk_note: "Liquidity is moderate; review price freshness.",
      latest_price_mad: 1040,
      daily_change_pct: 0.6,
      momentum_1m: 0.006,
      momentum_3m: 0.024,
    },
  ],
  signals: [
    {
      ticker: "ATW",
      signal_date: "2026-05-03",
      signal: "HOLD",
      confidence: 76,
      reason: "Quality and liquidity are strong, but sector exposure is already meaningful.",
      risk_note: "Watch banking concentration.",
      model_version: "mock-v1",
    },
    {
      ticker: "IAM",
      signal_date: "2026-05-03",
      signal: "BUY",
      confidence: 73,
      reason: "Defensive dividend profile fits balanced manual portfolios.",
      risk_note: "Confirm latest source timestamp before relying on signal.",
      model_version: "mock-v1",
    },
    {
      ticker: "LHM",
      signal_date: "2026-05-03",
      signal: "SELL",
      confidence: 69,
      reason: "Manual portfolio concentration is high relative to the risk profile.",
      risk_note: "Review single-name exposure.",
      model_version: "mock-v1",
    },
    {
      ticker: "BOA",
      signal_date: "2026-05-03",
      signal: "HOLD",
      confidence: 67,
      reason: "Momentum is improving, while banking-sector concentration remains a watch point.",
      risk_note: "Review banking-sector exposure before increasing allocation.",
      model_version: "mock-v1",
    },
    {
      ticker: "TQM",
      signal_date: "2026-05-03",
      signal: "HOLD",
      confidence: 63,
      reason: "Defensive profile is useful for monitoring, but signal strength is moderate.",
      risk_note: "Liquidity is moderate; review price freshness.",
      model_version: "mock-v1",
    },
  ],
  snapshots: [
    { ticker: "ATW", as_of: "2026-05-03T10:00:00Z", price_mad: 480, volume: 145000, momentum_90d: 0.072 },
    { ticker: "IAM", as_of: "2026-05-03T10:00:00Z", price_mad: 91, volume: 220000, momentum_90d: 0.031 },
    { ticker: "LHM", as_of: "2026-05-03T10:00:00Z", price_mad: 1780, volume: 9800, momentum_90d: 0.085 },
    { ticker: "TQM", as_of: "2026-05-03T10:00:00Z", price_mad: 1040, volume: 7600, momentum_90d: 0.024 },
    { ticker: "BOA", as_of: "2026-05-03T10:00:00Z", price_mad: 185, volume: 84000, momentum_90d: 0.066 },
  ],
  portfolio: {
    portfolio_id: "demo",
    portfolio_name: "Demo Manual Portfolio",
    base_currency: "MAD",
    cost_basis_mad: 141_320,
    current_value_mad: 145870,
    unrealized_pl_mad: 4550,
    unrealized_pl_pct: 3.22,
    sector_allocations: {
      Banking: 31.2,
      Telecom: 15.6,
      Materials: 36.6,
    },
    data_quality_warnings: [],
    holdings: [
      { ticker: "ATW", quantity: 60, average_cost_mad: 462, current_price_mad: 480, market_value_mad: 28800, unrealized_pl_mad: 1080, allocation_pct: 19.74, manual_note: "Core banking position" },
      { ticker: "IAM", quantity: 250, average_cost_mad: 91, current_price_mad: 91, market_value_mad: 22750, unrealized_pl_mad: 0, allocation_pct: 15.60, manual_note: "Defensive dividend exposure" },
      { ticker: "LHM", quantity: 30, average_cost_mad: 1780, current_price_mad: 1780, market_value_mad: 53400, unrealized_pl_mad: 0, allocation_pct: 36.61, manual_note: "High concentration, review" },
    ],
  },
  alerts: [
    { id: "1", severity: "High", alert_type: "single_stock_exposure", message: "LHM represents a large share of the manual portfolio.", symbol: "LHM", recommended_action: "Review position size and diversification. This app does not execute trades.", is_read: false },
    { id: "2", severity: "Medium", alert_type: "sector_exposure", message: "Banking exposure is above the review threshold.", recommended_action: "Review whether sector concentration matches the portfolio objective.", is_read: true },
  ],
  unreadAlerts: [
    { id: "1", severity: "High", alert_type: "single_stock_exposure", message: "LHM represents a large share of the manual portfolio.", symbol: "LHM", recommended_action: "Review position size and diversification. This app does not execute trades.", is_read: false },
  ],
  watchlists: [
    {
      id: "core",
      name: "Core Casablanca Watchlist",
      description: "Tracked Moroccan equities with research-only alerts.",
      is_default: true,
      items: [
        { ticker: "ATW", latest_price_mad: 480, signal: "HOLD", ranking_score: 84, daily_change_pct: 1.2, risk_level: "medium", alert_above_mad: 500 },
        { ticker: "IAM", latest_price_mad: 91, signal: "BUY", ranking_score: 79, daily_change_pct: -0.4, risk_level: "low", alert_below_mad: 88 },
        { ticker: "LHM", latest_price_mad: 1780, signal: "SELL", ranking_score: 74, daily_change_pct: -5.8, risk_level: "high" },
      ],
    },
  ],
};
